### ISSUE TITLE
npm ERR! peerinvalid The package react-native@0.21.0 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by karthickvkumar** [magicismight/react-native-toggle#1]
@magicismight  When i try to install in rn 0.21 it showing error: 
npm ERR! peerinvalid The package react-native@0.21.0 does not satisfy its siblings' peerDependencies requirements!
![selection_005](https://cloud.githubusercontent.com/assets/11032434/13626235/0c9f701c-e5e6-11e5-84d9-56ff2163b52f.png)

Thanks in Advance

**Comment by magicismight** [comment]
That is weird.
As you can see in [package.json](https://github.com/magicismight/react-native-toggle/blob/master/package.json), `react-native-toggle` do not have peerDependencies.
Can you try `npm install react-native-toggle@1.0.3 --save` ?

**Comment by karthickvkumar** [comment]
@magicismight  i tried npm install react-native-toggle@1.0.3 --save but still it showing the same error!
![selection_006](https://cloud.githubusercontent.com/assets/11032434/13663997/d13193d0-e6ca-11e5-82b0-04dc655c0e1e.png)

Thanks in Advance
